// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/trident.proto

package trident

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID primary key as assigned by PostgreSQL.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Strkey-encoded contract address (C...).
	ContractId string `protobuf:"bytes,2,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Ledger sequence number in which this event was emitted.
	LedgerSequence uint64 `protobuf:"varint,3,opt,name=ledger_sequence,json=ledgerSequence,proto3" json:"ledger_sequence,omitempty"`
	// ISO 8601 UTC timestamp of the ledger close.
	LedgerTimestamp string `protobuf:"bytes,4,opt,name=ledger_timestamp,json=ledgerTimestamp,proto3" json:"ledger_timestamp,omitempty"`
	// Hash of the transaction that emitted this event.
	TransactionHash string `protobuf:"bytes,5,opt,name=transaction_hash,json=transactionHash,proto3" json:"transaction_hash,omitempty"`
	// Zero-based index of this event within its transaction.
	EventIndex uint32 `protobuf:"varint,6,opt,name=event_index,json=eventIndex,proto3" json:"event_index,omitempty"`
	// "contract" | "system" | "diagnostic"
	EventType string `protobuf:"bytes,7,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// Decoded topic values in order. Serialised from ScVal to string.
	Topics []string `protobuf:"bytes,8,rep,name=topics,proto3" json:"topics,omitempty"`
	// Decoded event body as a JSON string. Complex types are serialised
	// recursively; i128/u128 values outside i64 range are JSON strings.
	Data string `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	// Row insertion timestamp (server time, not ledger time).
	CreatedAt     string `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_trident_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trident_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_proto_trident_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *Event) GetLedgerSequence() uint64 {
	if x != nil {
		return x.LedgerSequence
	}
	return 0
}

func (x *Event) GetLedgerTimestamp() string {
	if x != nil {
		return x.LedgerTimestamp
	}
	return ""
}

func (x *Event) GetTransactionHash() string {
	if x != nil {
		return x.TransactionHash
	}
	return ""
}

func (x *Event) GetEventIndex() uint32 {
	if x != nil {
		return x.EventIndex
	}
	return 0
}

func (x *Event) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *Event) GetTopics() []string {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *Event) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Event) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by contract address. Empty string means all contracts.
	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Filter by the value of the first topic (e.g. "transfer").
	Topic_0 string `protobuf:"bytes,2,opt,name=topic_0,json=topic0,proto3" json:"topic_0,omitempty"`
	// Filter by the value of the second topic.
	Topic_1 string `protobuf:"bytes,3,opt,name=topic_1,json=topic1,proto3" json:"topic_1,omitempty"`
	// Inclusive lower bound on ledger sequence.
	LedgerFrom uint64 `protobuf:"varint,4,opt,name=ledger_from,json=ledgerFrom,proto3" json:"ledger_from,omitempty"`
	// Inclusive upper bound on ledger sequence. 0 means no upper bound.
	LedgerTo uint64 `protobuf:"varint,5,opt,name=ledger_to,json=ledgerTo,proto3" json:"ledger_to,omitempty"`
	// Opaque cursor from the previous response. Empty string on first call.
	Cursor string `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// Maximum number of events to return. Capped server-side at 200.
	Limit         uint32 `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_proto_trident_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trident_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_trident_proto_rawDescGZIP(), []int{1}
}

func (x *ListEventsRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *ListEventsRequest) GetTopic_0() string {
	if x != nil {
		return x.Topic_0
	}
	return ""
}

func (x *ListEventsRequest) GetTopic_1() string {
	if x != nil {
		return x.Topic_1
	}
	return ""
}

func (x *ListEventsRequest) GetLedgerFrom() uint64 {
	if x != nil {
		return x.LedgerFrom
	}
	return 0
}

func (x *ListEventsRequest) GetLedgerTo() uint64 {
	if x != nil {
		return x.LedgerTo
	}
	return 0
}

func (x *ListEventsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListEventsRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEventsResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Events []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// Pass this as `cursor` on the next call to fetch the next page.
	// Empty string when there are no more results.
	NextCursor    string `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_proto_trident_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trident_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_trident_proto_rawDescGZIP(), []int{2}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListEventsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetEventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID of the event to fetch.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_proto_trident_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trident_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_trident_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StreamEventsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contract address to subscribe to. Required.
	ContractId string `protobuf:"bytes,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	// Optional topic_0 filter — only events whose first topic matches are pushed.
	Topic_0       string `protobuf:"bytes,2,opt,name=topic_0,json=topic0,proto3" json:"topic_0,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_proto_trident_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trident_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_trident_proto_rawDescGZIP(), []int{4}
}

func (x *StreamEventsRequest) GetContractId() string {
	if x != nil {
		return x.ContractId
	}
	return ""
}

func (x *StreamEventsRequest) GetTopic_0() string {
	if x != nil {
		return x.Topic_0
	}
	return ""
}

var File_proto_trident_proto protoreflect.FileDescriptor

const file_proto_trident_proto_rawDesc = "" +
	"\n" +
	"\x13proto/trident.proto\x12\atrident\"\xc2\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcontract_id\x18\x02 \x01(\tR\n" +
	"contractId\x12'\n" +
	"\x0fledger_sequence\x18\x03 \x01(\x04R\x0eledgerSequence\x12)\n" +
	"\x10ledger_timestamp\x18\x04 \x01(\tR\x0fledgerTimestamp\x12)\n" +
	"\x10transaction_hash\x18\x05 \x01(\tR\x0ftransactionHash\x12\x1f\n" +
	"\vevent_index\x18\x06 \x01(\rR\n" +
	"eventIndex\x12\x1d\n" +
	"\n" +
	"event_type\x18\a \x01(\tR\teventType\x12\x16\n" +
	"\x06topics\x18\b \x03(\tR\x06topics\x12\x12\n" +
	"\x04data\x18\t \x01(\tR\x04data\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt\"\xd2\x01\n" +
	"\x11ListEventsRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x17\n" +
	"\atopic_0\x18\x02 \x01(\tR\x06topic0\x12\x17\n" +
	"\atopic_1\x18\x03 \x01(\tR\x06topic1\x12\x1f\n" +
	"\vledger_from\x18\x04 \x01(\x04R\n" +
	"ledgerFrom\x12\x1b\n" +
	"\tledger_to\x18\x05 \x01(\x04R\bledgerTo\x12\x16\n" +
	"\x06cursor\x18\x06 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\a \x01(\rR\x05limit\"x\n" +
	"\x12ListEventsResponse\x12&\n" +
	"\x06events\x18\x01 \x03(\v2\x0e.trident.EventR\x06events\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"!\n" +
	"\x0fGetEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"O\n" +
	"\x13StreamEventsRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\tR\n" +
	"contractId\x12\x17\n" +
	"\atopic_0\x18\x02 \x01(\tR\x06topic02\xc5\x01\n" +
	"\x06Events\x12E\n" +
	"\n" +
	"ListEvents\x12\x1a.trident.ListEventsRequest\x1a\x1b.trident.ListEventsResponse\x124\n" +
	"\bGetEvent\x12\x18.trident.GetEventRequest\x1a\x0e.trident.Event\x12>\n" +
	"\fStreamEvents\x12\x1c.trident.StreamEventsRequest\x1a\x0e.trident.Event0\x01B;Z9github.com/Depo-dev/trident/services/api/internal/tridentb\x06proto3"

var (
	file_proto_trident_proto_rawDescOnce sync.Once
	file_proto_trident_proto_rawDescData []byte
)

func file_proto_trident_proto_rawDescGZIP() []byte {
	file_proto_trident_proto_rawDescOnce.Do(func() {
		file_proto_trident_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_trident_proto_rawDesc), len(file_proto_trident_proto_rawDesc)))
	})
	return file_proto_trident_proto_rawDescData
}

var file_proto_trident_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_trident_proto_goTypes = []any{
	(*Event)(nil),               // 0: trident.Event
	(*ListEventsRequest)(nil),   // 1: trident.ListEventsRequest
	(*ListEventsResponse)(nil),  // 2: trident.ListEventsResponse
	(*GetEventRequest)(nil),     // 3: trident.GetEventRequest
	(*StreamEventsRequest)(nil), // 4: trident.StreamEventsRequest
}
var file_proto_trident_proto_depIdxs = []int32{
	0, // 0: trident.ListEventsResponse.events:type_name -> trident.Event
	1, // 1: trident.Events.ListEvents:input_type -> trident.ListEventsRequest
	3, // 2: trident.Events.GetEvent:input_type -> trident.GetEventRequest
	4, // 3: trident.Events.StreamEvents:input_type -> trident.StreamEventsRequest
	2, // 4: trident.Events.ListEvents:output_type -> trident.ListEventsResponse
	0, // 5: trident.Events.GetEvent:output_type -> trident.Event
	0, // 6: trident.Events.StreamEvents:output_type -> trident.Event
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_trident_proto_init() }
func file_proto_trident_proto_init() {
	if File_proto_trident_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_trident_proto_rawDesc), len(file_proto_trident_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_trident_proto_goTypes,
		DependencyIndexes: file_proto_trident_proto_depIdxs,
		MessageInfos:      file_proto_trident_proto_msgTypes,
	}.Build()
	File_proto_trident_proto = out.File
	file_proto_trident_proto_goTypes = nil
	file_proto_trident_proto_depIdxs = nil
}
