apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "trident.fullname" . }}-go-api
  labels:
    {{- include "trident.labels" . | nindent 4 }}
    app.kubernetes.io/component: go-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "trident.fullname" . }}-go-api
  minReplicas: {{ .Values.goApi.hpa.minReplicas }}
  maxReplicas: {{ .Values.goApi.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.goApi.hpa.targetCPUUtilizationPercentage }}
