/**
 * This file is auto-generated from api/openapi.yaml
 * Do not edit manually. Run 'npm run generate:types' to regenerate.
 * Generated by openapi-typescript
 */

export interface paths {
  "/v1/health": {
    get: operations["getHealth"];
  };
  "/v1/events": {
    get: operations["listEvents"];
  };
  "/v1/events/{id}": {
    get: operations["getEvent"];
  };
  "/v1/events/stream": {
    get: operations["streamEvents"];
  };
  "/v1/stats/contracts": {
    get: operations["getContractStats"];
  };
  "/v1/admin/db": {
    get: operations["getAdminDBStats"];
  };
}

export type operations = {
  getHealth: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  listEvents: {
    parameters: {
      query?: {
        contract_id?: string;
        topic_0?: string;
        topic_1?: string;
        event_type?: "contract" | "system" | "diagnostic";
        from_ledger?: number;
        to_ledger?: number;
        limit?: number;
        cursor?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["EventListResponse"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getEvent: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": {
            event: components["schemas"]["SorobanEvent"];
          };
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      404: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  streamEvents: {
    parameters: {
      query?: {
        topic_0?: string;
      };
    };
    responses: {
      200: {
        content: {
          "text/event-stream": Record<string, unknown>;
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getContractStats: {
    parameters: {
      query?: {
        from_ledger?: number;
        to_ledger?: number;
        network?: "testnet" | "mainnet";
        limit?: number;
      };
    };
    responses: {
      200: {
        headers: {
          "Cache-Control"?: string;
          "X-Cache"?: "HIT" | "MISS";
        };
        content: {
          "application/json": components["schemas"]["ContractStatsResponse"];
        };
      };
      400: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  getAdminDBStats: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AdminDBStatsResponse"];
        };
      };
      401: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      503: {
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
};

export type components = {
  schemas: {
    SorobanEvent: {
      id: string;
      contract_id: string;
      ledger_sequence: number;
      ledger_timestamp: string;
      transaction_hash: string;
      event_index: number;
      event_type: "contract" | "system" | "diagnostic";
      topics: string[];
      data: string;
      created_at: string;
    };
    EventListResponse: {
      events: components["schemas"]["SorobanEvent"][];
      has_more: boolean;
      next_cursor?: string | null;
    };
    ContractStats: {
      contract_id: string;
      event_count: number;
      last_seen_ledger: number;
      last_seen_at: string;
    };
    ContractStatsResponse: {
      contracts: components["schemas"]["ContractStats"][];
      from_ledger: number;
      to_ledger: number;
      network: "testnet" | "mainnet";
      generated_at: string;
    };
    HealthResponse: {
      status: "ok" | "degraded" | "down";
      database?: {
        status: "ok" | "down";
        latency_ms?: number;
      };
      version?: string;
    };
    AdminDBStatsResponse: {
      connections: {
        active: number;
        idle: number;
        max: number;
      };
      pgbouncer?: Record<string, unknown> | null;
    };
    ErrorResponse: {
      error: string;
      code:
        | "INVALID_ARGUMENT"
        | "NOT_FOUND"
        | "UNAUTHORIZED"
        | "RATE_LIMITED"
        | "INTERNAL";
    };
  };
};
