/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns indexer health status and last indexed ledger
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Soroban contract events
         * @description Query events with optional filtering by contract, topics, and ledger range
         */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single event by ID
         * @description Retrieve a specific event by its UUID
         */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream events (Server-Sent Events)
         * @description Real-time event stream using Server-Sent Events (SSE)
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get multiple events by ID
         * @description Retrieve multiple events in a single request (up to 100 ids).
         *
         *     Batch contract:
         *     - `events` and `missing` both preserve the request order of `ids`.
         *     - Duplicate ids are deduplicated on first occurrence; each unique id
         *       appears at most once in the response, in `events` or in `missing`.
         *     - A request with more than 100 ids (duplicates included) is rejected
         *       with `400 INVALID_ARGUMENT`; so is any id that is not a UUID v4.
         *     - Ids that are valid but not indexed do not fail the request; they
         *       are listed in `missing` and the found events are still returned.
         */
        post: operations["batchGetEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contracts/{id}/events/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get per-contract event schemas
         * @description Returns the observed event names and typed field schemas for one contract version.
         */
        get: operations["getContractEventSchemas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contracts/{id}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a contract's parsed spec and detected interfaces
         * @description Returns the functions captured from a tracked contract's spec (contractmeta / SEP-48) and the standard interfaces detected from them (e.g. SEP-41 token, NFT).
         */
        get: operations["getContractSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contracts/{id}/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a contract's latest storage snapshot values
         * @description Returns the most recently observed value for every storage key snapshotted for a tracked contract.
         */
        get: operations["getContractStorageLatest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contracts/{id}/storage/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the change history of a single contract storage key
         * @description Returns every recorded change for one storage key, oldest first, for a tracked contract.
         */
        get: operations["getContractStorageHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats/indexer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get indexer statistics
         * @description Returns real-time indexer health metrics, throughput, and the public data-freshness contract (lag_ledgers, lag_seconds_estimated, last_ledger_indexed) — see docs/observability/data-freshness.md
         */
        get: operations["getIndexerStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get contract activity statistics
         * @description Returns contracts sorted by event count with optional ledger range filtering
         */
        get: operations["getContractStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List API keys
         * @description List all API keys (admin only)
         */
        get: operations["listApiKeys"];
        put?: never;
        /**
         * Create an API key
         * @description Generate a new API key for authentication
         */
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an API key
         * @description Revoke and delete an API key (admin only)
         */
        delete: operations["deleteApiKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Database admin statistics
         * @description Returns database and connection pool statistics (admin only)
         */
        get: operations["getAdminDbStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Exposes Prometheus-formatted metrics
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SorobanEvent: {
            /**
             * Format: uuid
             * @description Unique event identifier
             */
            id: string;
            /** @description Soroban contract address */
            contract_id: string;
            /**
             * Format: uint64
             * @description Ledger sequence number
             */
            ledger_sequence: number;
            /**
             * Format: date-time
             * @description Ledger timestamp in ISO 8601 format
             */
            ledger_timestamp: string;
            /** @description Transaction hash (XDR-encoded) */
            transaction_hash: string;
            /**
             * Format: uint32
             * @description Event index within transaction
             */
            event_index: number;
            /**
             * @description Type of event
             * @enum {string}
             */
            event_type: "contract" | "system" | "diagnostic";
            /** @description Event topics (XDR-encoded) */
            topics: string[];
            /** @description Event data (XDR-encoded) */
            data: string;
            /**
             * Format: date-time
             * @description Timestamp when event was indexed
             */
            created_at: string;
        };
        EventListResponse: {
            /** @description List of events */
            events: components["schemas"]["SorobanEvent"][];
            /** @description Whether more results are available */
            has_more: boolean;
            /** @description Opaque cursor for next page (null if has_more is false) */
            next_cursor?: string | null;
        };
        HealthResponse: {
            /**
             * @description Overall system status
             * @enum {string}
             */
            status: "ok" | "degraded";
            indexer: {
                /**
                 * Format: int64
                 * @description Latest indexed ledger sequence
                 */
                last_ledger_indexed: number | null;
                /**
                 * Format: date-time
                 * @description Timestamp of last successful indexer poll
                 */
                last_poll_at?: string | null;
            };
        };
        IndexerStatsResponse: {
            /**
             * @description Indexer health status
             * @enum {string}
             */
            status: "healthy" | "lagging" | "stalled";
            /** @description Network name from NETWORK environment variable */
            network: string;
            /**
             * Format: int64
             * @description Latest indexed ledger sequence
             */
            last_ledger_indexed?: number | null;
            /**
             * Format: int64
             * @description Current chain tip ledger (from RPC)
             */
            chain_tip_ledger?: number | null;
            /**
             * Format: int64
             * @description Number of ledgers behind chain tip
             */
            lag_ledgers?: number | null;
            /**
             * Format: double
             * @description Estimated wall-clock staleness in seconds: lag_ledgers times Stellar's protocol-target ledger close time (~5s). Null whenever lag_ledgers is null. See docs/observability/data-freshness.md for the full freshness contract this field is part of.
             */
            lag_seconds_estimated?: number | null;
            /**
             * Format: int64
             * @description Cumulative events indexed
             */
            events_indexed_total?: number | null;
            /**
             * Format: int32
             * @description Events processed in last poll
             */
            events_last_poll?: number | null;
            /**
             * Format: int32
             * @description Average poll duration in milliseconds
             */
            avg_poll_duration_ms?: number | null;
            /**
             * Format: date-time
             * @description Timestamp of last successful poll
             */
            last_poll_at?: string | null;
        };
        TokenMetadataResponse: {
            /** @description Soroban contract address */
            contract_id: string;
            /**
             * @description Network queried
             * @enum {string}
             */
            network: "testnet" | "mainnet";
            /** @description True when the contract was resolved and implements the SEP-41 read interface. False for both "not yet resolved" and "resolved, not a token". */
            is_token: boolean;
            /** @description Token name, from name(). Null unless is_token is true. */
            name?: string | null;
            /** @description Token symbol, from symbol(). Null unless is_token is true. */
            symbol?: string | null;
            /**
             * Format: int32
             * @description Token decimals, from decimals(). Null unless is_token is true.
             */
            decimals?: number | null;
            /**
             * Format: date-time
             * @description When this contract was last resolved. Null if never resolved.
             */
            resolved_at?: string | null;
        };
        ContractEventSchemaResponse: {
            /** @description Soroban contract address */
            contract_id: string;
            /**
             * @description Network queried
             * @enum {string}
             */
            network: "testnet" | "mainnet";
            /** @description Contract code hash for this schema version */
            code_hash: string;
            /** @description Observed event names and their typed field schemas */
            events: components["schemas"]["ContractEventSchema"][];
        };
        ContractEventSchema: {
            /** @description Contract event name (topic_0) */
            event_name: string;
            /** @description Named fields for this event payload */
            fields: components["schemas"]["ContractEventFieldSchema"][];
        };
        ContractEventFieldSchema: {
            /** @description Stable field name for this event payload position or property */
            name: string;
            /** @description Field type inferred from the contract interface or observed payloads */
            type: string;
        };
        ContractSpecResponse: {
            /** @description Soroban contract address */
            contract_id: string;
            /**
             * @description Network queried
             * @enum {string}
             */
            network: "testnet" | "mainnet";
            /** @description Deployed WASM code hash this spec was parsed from */
            code_hash: string;
            /** @description Whether an embedded contractspecv0 section was found */
            has_spec: boolean;
            /** @description Primary classification derived from detected interfaces (e.g. token, nft, custom) */
            contract_type: string;
            /** @description Every standard interface detected from the contract's spec functions */
            interfaces: string[];
            /** @description Functions captured from the contract's spec */
            functions: components["schemas"]["ContractSpecFunction"][];
        };
        ContractSpecFunction: {
            /** @description Exported function name */
            name: string;
        };
        ContractStorageResponse: {
            /** @description Soroban contract address */
            contract_id: string;
            /**
             * @description Network queried
             * @enum {string}
             */
            network: "testnet" | "mainnet";
            /** @description Storage snapshot values (latest, or full history when queried via /storage/history) */
            values: components["schemas"]["ContractStorageValue"][];
        };
        ContractStorageValue: {
            /** @description Base64-encoded XDR LedgerKey this value was read from */
            storage_key: string;
            /** @description Human-readable decoded storage key */
            key: unknown;
            /** @description Human-readable decoded value (absent when the entry was removed) */
            value?: unknown;
            /**
             * Format: int64
             * @description Ledger sequence at which this value was observed
             */
            ledger_sequence: number;
            /**
             * Format: date-time
             * @description Timestamp this snapshot row was recorded
             */
            observed_at: string;
        };
        ContractStatsResponse: {
            /** @description Contracts sorted by event count (descending) */
            contracts: components["schemas"]["ContractStats"][];
            /**
             * Format: int64
             * @description Lower bound of queried ledger range
             */
            from_ledger: number;
            /**
             * Format: int64
             * @description Upper bound of queried ledger range
             */
            to_ledger: number;
            /**
             * @description Network queried
             * @enum {string}
             */
            network: "testnet" | "mainnet";
            /**
             * Format: date-time
             * @description Timestamp when response was generated
             */
            generated_at: string;
        };
        ContractStats: {
            /** @description Soroban contract address */
            contract_id: string;
            /**
             * Format: int64
             * @description Total events for this contract in range
             */
            event_count: number;
            /**
             * Format: int64
             * @description Latest ledger sequence for this contract
             */
            last_seen_ledger: number;
            /**
             * Format: date-time
             * @description Timestamp of last event for this contract
             */
            last_seen_at: string;
        };
        ErrorResponse: {
            error: {
                /** @description Error code (e.g., INVALID_ARGUMENT, INTERNAL, UNAVAILABLE) */
                code: string;
                /** @description Human-readable error message */
                message: string;
                /** @description Request ID for debugging */
                request_id?: string;
            };
        };
    };
    responses: {
        /** @description Invalid request parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Requested resource was not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Service temporarily unavailable */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indexer is healthy or degraded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                /**
                 * @description Filter by Soroban contract address (strkey format, 56 chars starting with C)
                 * @example CAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2KM
                 */
                contract_id?: string;
                /** @description Filter by primary topic (XDR-encoded) */
                topic_0?: string;
                /** @description Filter by secondary topic (XDR-encoded) */
                topic_1?: string;
                /** @description Lower bound of ledger range (inclusive) */
                from_ledger?: number;
                /** @description Upper bound of ledger range (inclusive) */
                to_ledger?: number;
                /** @description Network to query */
                network?: "testnet" | "mainnet";
                /** @description Maximum number of events to return */
                limit?: number;
                /** @description Opaque pagination cursor from previous response (for next page) */
                after?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of events with pagination metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Event UUID (v4)
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        event: components["schemas"]["SorobanEvent"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    streamEvents: {
        parameters: {
            query: {
                /** @description Contract to subscribe to */
                contract_id: string;
                /** @description Optional topic filter */
                topic_0?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": Record<string, never>;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    batchGetEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description List of event UUIDs. Duplicates are deduplicated on first occurrence; the 100-id limit counts duplicates. */
                    ids: string[];
                };
            };
        };
        responses: {
            /**
             * @description Batch result. Always returns 200 even when some IDs are not found;
             *     check `missing` for unresolved IDs.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Found events, in request order (deduplicated). */
                        events: components["schemas"]["SorobanEvent"][];
                        /** @description Ids that are valid UUIDs but not indexed, in request order. Empty array when every id was found. */
                        missing: string[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getContractEventSchemas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Soroban contract address */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contract event schema registry entry */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractEventSchemaResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getContractSpec: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Soroban contract address */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contract spec and detected interfaces */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractSpecResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getContractStorageLatest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Soroban contract address */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest known value per storage key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractStorageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getContractStorageHistory: {
        parameters: {
            query: {
                /** @description Storage key to fetch history for, as returned by the storage/spec endpoints */
                key: string;
            };
            header?: never;
            path: {
                /** @description Soroban contract address */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recorded changes for the requested storage key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractStorageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getIndexerStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indexer statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexerStatsResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getContractStats: {
        parameters: {
            query?: {
                /** @description Lower bound of ledger range (inclusive, default 0 for all time) */
                from_ledger?: number;
                /** @description Upper bound of ledger range (inclusive, default latest indexed) */
                to_ledger?: number;
                /** @description Network to query */
                network?: "testnet" | "mainnet";
                /** @description Number of top contracts to return */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contract activity statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractStatsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of API keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        keys?: {
                            /** Format: uuid */
                            id?: string;
                            key_prefix?: string;
                            label?: string;
                            network?: string;
                            rate_limit_tier?: string;
                            /** Format: date-time */
                            last_used_at?: string;
                            request_count?: number;
                            /** Format: date-time */
                            created_at?: string;
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Human-readable label for this key */
                    label?: string;
                    /**
                     * @description Network this key is associated with
                     * @default mainnet
                     * @enum {string}
                     */
                    network?: "testnet" | "mainnet";
                    /**
                     * @description Rate limit tier for this key
                     * @default standard
                     * @enum {string}
                     */
                    rate_limit_tier?: "free" | "standard" | "premium" | "internal";
                };
            };
        };
        responses: {
            /** @description API key created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id?: string;
                        /** @description The raw API key (shown only once) */
                        key?: string;
                        /** @description First 16 characters of key for reference */
                        key_prefix?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description API key ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description API key not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAdminDbStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain; version=0.0.4": string;
                };
            };
        };
    };
}
