/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Cheap process-liveness check (issue #243) — no dependency calls (no Postgres/Redis/gRPC). Always 200 while the process is up and serving requests. Intended for Kubernetes' liveness probe. For dependency health (Postgres/Redis/gRPC), see GET /v1/ready instead.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness check
         * @description Verifies Postgres, Redis, and the gRPC backend concurrently, each with a 3-second timeout (issue #243). Returns 503 if any dependency check fails. Intended for Kubernetes' readiness probe / Fly's HTTP service check, so a pod with a broken dependency is pulled out of rotation instead of continuing to receive traffic it can't serve.
         */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Build and schema version
         * @description Reports which build is running — semantic version tag, git commit SHA, build timestamp, and the highest applied database migration (issue #397). Answers "which build is live?" during an incident without reading GHCR tags or pod specs.
         *     Authenticated: the commit SHA and schema version narrow the search for known-vulnerable code paths, so this is not public. Use /v1/ready for an unauthenticated liveness signal.
         *     When the database is unreachable the endpoint still returns 200 with build metadata and a null schema_version, so it stays usable during exactly the outage you need it for.
         */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Soroban contract events
         * @description Query events with optional filtering by contract, topics, and ledger range
         */
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single event by ID
         * @description Retrieve a specific event by its UUID
         */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream events (Server-Sent Events)
         * @description Real-time event stream using Server-Sent Events (SSE)
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get multiple events by ID
         * @description Retrieve multiple events in a single request (up to 100 ids).
         *
         *     Batch contract:
         *     - `events` and `missing` both preserve the request order of `ids`.
         *     - Duplicate ids are deduplicated on first occurrence; each unique id
         *       appears at most once in the response, in `events` or in `missing`.
         *     - A request with more than 100 ids (duplicates included) is rejected
         *       with `400 INVALID_ARGUMENT`; so is any id that is not a UUID v4.
         *     - Ids that are valid but not indexed do not fail the request; they
         *       are listed in `missing` and the found events are still returned.
         */
        post: operations["batchGetEvents"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contracts/{id}/events/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get per-contract event schemas
         * @description Returns the observed event names and typed field schemas for one contract version.
         */
        get: operations["getContractEventSchemas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contracts/{id}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a contract's parsed spec and detected interfaces
         * @description Returns the functions captured from a tracked contract's spec (contractmeta / SEP-48) and the standard interfaces detected from them (e.g. SEP-41 token, NFT).
         */
        get: operations["getContractSpec"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contracts/{id}/storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a contract's latest storage snapshot values
         * @description Returns the most recently observed value for every storage key snapshotted for a tracked contract.
         */
        get: operations["getContractStorageLatest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contracts/{id}/storage/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the change history of a single contract storage key
         * @description Returns every recorded change for one storage key, oldest first, for a tracked contract.
         */
        get: operations["getContractStorageHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats/indexer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get indexer statistics
         * @description Returns real-time indexer health metrics, throughput, and the public data-freshness contract (lag_ledgers, lag_seconds_estimated, last_ledger_indexed) — see docs/observability/data-freshness.md
         */
        get: operations["getIndexerStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get contract activity statistics
         * @description Returns contracts sorted by event count with optional ledger range filtering
         */
        get: operations["getContractStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List API keys
         * @description List API keys (admin only), keyset-paginated (issue #220). Ordered newest first (created_at DESC, id DESC as tiebreaker); cursor is opaque — never construct or parse it, just pass back the value returned in next_cursor.
         */
        get: operations["listApiKeys"];
        put?: never;
        /**
         * Create an API key
         * @description Generate a new API key for authentication
         */
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an API key
         * @description Revoke and delete an API key (admin only)
         */
        delete: operations["deleteApiKey"];
        options?: never;
        head?: never;
        /**
         * Update an API key
         * @description Update an API key's label and/or rate-limit tier (admin only). At least one of the two fields must be present. A tier change takes effect immediately — the shared tier cache is invalidated on success. Only active (non-revoked) keys can be updated.
         */
        patch: operations["updateApiKey"];
        trace?: never;
    };
    "/v1/admin/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Database admin statistics
         * @description Returns database and connection pool statistics (admin only)
         */
        get: operations["getAdminDbStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/keys/{id}/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * API key usage report
         * @description Per-key usage over a time window (admin only), aggregated from the audit log. Both `from` and `to` are required RFC 3339 timestamps; the window may not exceed 31 days. Unknown query parameters are rejected.
         */
        get: operations["getAdminKeyUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List registered contracts
         * @description Keyset-paginated list of contracts registered for indexing (admin only). `limit` outside 1..200 silently falls back to the default of 100; unknown query parameters are ignored.
         */
        get: operations["listAdminContracts"];
        put?: never;
        /**
         * Register a contract for indexing
         * @description Register (or re-register) a contract in the indexing allowlist (admin only). Upserts on (contract_id, network) — re-registering an existing contract updates its label and index_from and still returns 201.
         */
        post: operations["createAdminContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/contracts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Unregister a contract
         * @description Remove a contract registration by its registration ID (the `id` returned at registration, not the contract address). Idempotent — deleting a non-existent registration still returns 204.
         */
        delete: operations["deleteAdminContract"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/contracts/{id}/call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Simulate a read-only contract call
         * @description Simulate a contract function invocation via Soroban RPC and return the decoded result. Nothing is submitted to the network. Note the three success shapes: a simulation-level failure still returns HTTP 200 with `success: false` and `error` set; a result that cannot be decoded returns `success: true` with only `raw_xdr`.
         */
        post: operations["callContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List webhook subscriptions
         * @description Webhook subscriptions owned by the calling API key. Includes each subscription's signing secret. Returns JSON null (not an empty array) when the key owns no subscriptions. Webhook endpoints are not yet part of the frozen v1 surface; some of their error responses are plain text rather than the canonical error envelope.
         */
        get: operations["listWebhooks"];
        put?: never;
        /**
         * Create a webhook subscription
         * @description Subscribe a target URL to events from a contract. Target URLs must be https, resolve publicly, and not point at private, loopback, link-local, or metadata addresses. The returned secret signs every delivery. Note the camelCase field names — webhook endpoints predate the snake_case convention and are not yet part of the frozen v1 surface.
         */
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a webhook subscription
         * @description Permanently delete a webhook subscription and stop its deliveries.
         */
        delete: operations["deleteWebhook"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}/rotate-secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a webhook signing secret
         * @description Generate a new primary signing secret for the subscription, demoting the current one to secondary in the same statement so in-flight deliveries signed with the old secret still verify. Scoped to the caller's API key: rotating another tenant's subscription returns 404. Requires a database-backed API key; legacy env-hash authentication carries no key identity to scope ownership to.
         */
        post: operations["rotateWebhookSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Pause webhook deliveries
         * @description Pause deliveries for a subscription. Returns the paused status even when the ID matches no subscription (no existence check).
         */
        patch: operations["pauseWebhook"];
        trace?: never;
    };
    "/v1/webhooks/{id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Resume webhook deliveries
         * @description Resume deliveries for a paused subscription. Returns the resumed status even when the ID matches no subscription (no existence check).
         */
        patch: operations["resumeWebhook"];
        trace?: never;
    };
    "/v1/webhooks/{id}/deliveries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recent webhook deliveries
         * @description The 100 most recent delivery attempts for a subscription, newest first. Returns JSON null (not an empty array) when there are none.
         */
        get: operations["listWebhookDeliveries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}/dead-letters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List dead-lettered deliveries
         * @description Deliveries that exhausted their retries (status dead_lettered), up to 200, newest first. Always an array — empty when there are none.
         */
        get: operations["listWebhookDeadLetters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/webhooks/{id}/dead-letters/{deliveryId}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay a dead-lettered delivery
         * @description Re-attempt one dead-lettered delivery and record the outcome. The response reports the replay result in snake_case (unlike the other webhook endpoints).
         */
        post: operations["replayWebhookDeadLetter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics
         * @description Exposes Prometheus-formatted metrics
         */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SorobanEvent: {
            /**
             * Format: uuid
             * @description Unique event identifier
             */
            id: string;
            /** @description Soroban contract address */
            contract_id: string;
            /**
             * Format: uint64
             * @description Ledger sequence number
             */
            ledger_sequence: number;
            /**
             * Format: date-time
             * @description Ledger timestamp in ISO 8601 format
             */
            ledger_timestamp: string;
            /** @description Transaction hash (XDR-encoded) */
            transaction_hash: string;
            /**
             * Format: uint32
             * @description Event index within transaction
             */
            event_index: number;
            /**
             * @description Type of event
             * @enum {string}
             */
            event_type: "contract" | "system" | "diagnostic";
            /** @description Event topics (XDR-encoded) */
            topics: string[];
            /** @description Event data (XDR-encoded) */
            data: string;
            /**
             * Format: date-time
             * @description Timestamp when event was indexed
             */
            created_at: string;
        };
        EventListResponse: {
            /** @description List of events */
            events: components["schemas"]["SorobanEvent"][];
            /** @description Whether more results are available */
            has_more: boolean;
            /** @description Opaque cursor for next page (null if has_more is false) */
            next_cursor: string | null;
        };
        LivenessResponse: {
            /**
             * @description Always "ok" while the process is up — no dependency checks.
             * @enum {string}
             */
            status: "ok";
        };
        ReadyChecks: {
            /** @description "ok" or "error: <message>" */
            postgres: string;
            /** @description "ok" or "error: <message>" */
            redis: string;
            /** @description "ok" or "error: <message>" */
            grpc_api: string;
        };
        ReadyResponse: {
            /**
             * @description "degraded" when any dependency check in `checks` failed.
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Format: int64
             * @description Ledgers behind chain tip, from system_state. Null when Postgres is unreachable or the chain-tip cache hasn't been populated yet.
             */
            indexer_lag: number | null;
            checks: components["schemas"]["ReadyChecks"];
        };
        VersionResponse: {
            /**
             * @description Semantic version tag of the running build, or "dev" for a binary built without release ldflags.
             * @example v1.2.3
             */
            version: string;
            /**
             * @description Full git commit SHA the binary was built from, or "unknown" when not injected at build time.
             * @example 2e6ad17c8f9b4a1d3e5f7a9c2b4d6e8f0a1c3e5d
             */
            commit_sha: string;
            /**
             * @description RFC 3339 build time, or "unknown" when not injected at build time. Not typed as date-time because of that sentinel.
             * @example 2026-08-26T15:19:00Z
             */
            build_timestamp: string;
            /** @description Highest applied migration version from _sqlx_migrations, as a string. Null when no migrations have been applied yet or when Postgres is unreachable — the endpoint still returns 200 in that case so build metadata stays available during an outage. */
            schema_version: string | null;
        };
        IndexerStatsResponse: {
            /**
             * @description Indexer health status
             * @enum {string}
             */
            status: "healthy" | "lagging" | "stalled";
            /** @description Network name from NETWORK environment variable */
            network: string;
            /**
             * Format: int64
             * @description Latest indexed ledger sequence
             */
            last_ledger_indexed: number | null;
            /**
             * Format: int64
             * @description Current chain tip ledger (from RPC)
             */
            chain_tip_ledger: number | null;
            /**
             * Format: int64
             * @description Number of ledgers behind chain tip
             */
            lag_ledgers: number | null;
            /**
             * Format: double
             * @description Estimated wall-clock staleness in seconds: lag_ledgers times Stellar's protocol-target ledger close time (~5s). Null whenever lag_ledgers is null. See docs/observability/data-freshness.md for the full freshness contract this field is part of.
             */
            lag_seconds_estimated: number | null;
            /**
             * Format: int64
             * @description Cumulative events indexed
             */
            events_indexed_total: number | null;
            /**
             * Format: int32
             * @description Events processed in last poll
             */
            events_last_poll: number | null;
            /**
             * Format: int32
             * @description Average poll duration in milliseconds
             */
            avg_poll_duration_ms: number | null;
            /**
             * Format: date-time
             * @description Timestamp of last successful poll
             */
            last_poll_at: string | null;
        };
        TokenMetadataResponse: {
            /** @description Soroban contract address */
            contract_id: string;
            /**
             * @description Network queried
             * @enum {string}
             */
            network: "testnet" | "mainnet";
            /** @description True when the contract was resolved and implements the SEP-41 read interface. False for both "not yet resolved" and "resolved, not a token". */
            is_token: boolean;
            /** @description Token name, from name(). Null unless is_token is true. */
            name?: string | null;
            /** @description Token symbol, from symbol(). Null unless is_token is true. */
            symbol?: string | null;
            /**
             * Format: int32
             * @description Token decimals, from decimals(). Null unless is_token is true.
             */
            decimals?: number | null;
            /**
             * Format: date-time
             * @description When this contract was last resolved. Null if never resolved.
             */
            resolved_at?: string | null;
        };
        ContractEventSchemaResponse: {
            /** @description Soroban contract address */
            contract_id: string;
            /**
             * @description Network queried
             * @enum {string}
             */
            network: "testnet" | "mainnet";
            /** @description Contract code hash for this schema version */
            code_hash: string;
            /** @description Observed event names and their typed field schemas */
            events: components["schemas"]["ContractEventSchema"][];
        };
        ContractEventSchema: {
            /** @description Contract event name (topic_0) */
            event_name: string;
            /** @description Named fields for this event payload */
            fields: components["schemas"]["ContractEventFieldSchema"][];
        };
        ContractEventFieldSchema: {
            /** @description Stable field name for this event payload position or property */
            name: string;
            /** @description Field type inferred from the contract interface or observed payloads */
            type: string;
        };
        ContractSpecResponse: {
            /** @description Soroban contract address */
            contract_id: string;
            /**
             * @description Network queried
             * @enum {string}
             */
            network: "testnet" | "mainnet";
            /** @description Deployed WASM code hash this spec was parsed from */
            code_hash: string;
            /** @description Whether an embedded contractspecv0 section was found */
            has_spec: boolean;
            /** @description Primary classification derived from detected interfaces (e.g. token, nft, custom) */
            contract_type: string;
            /** @description Every standard interface detected from the contract's spec functions */
            interfaces: string[];
            /** @description Functions captured from the contract's spec */
            functions: components["schemas"]["ContractSpecFunction"][];
        };
        ContractSpecFunction: {
            /** @description Exported function name */
            name: string;
        };
        ContractStorageResponse: {
            /** @description Soroban contract address */
            contract_id: string;
            /**
             * @description Network queried
             * @enum {string}
             */
            network: "testnet" | "mainnet";
            /** @description Storage snapshot values (latest, or full history when queried via /storage/history) */
            values: components["schemas"]["ContractStorageValue"][];
        };
        ContractStorageHistoryResponse: {
            /** @description The contract whose storage history was queried */
            contract_id: string;
            /** @description Network the contract is indexed on */
            network: string;
            /** @description The storage key whose history was queried */
            storage_key: string;
            /** @description Storage history entries, oldest first */
            values: components["schemas"]["ContractStorageValue"][];
            /** @description Whether more pages are available */
            has_more: boolean;
            /** @description Opaque cursor to pass as the cursor parameter for the next page */
            next_cursor?: string | null;
        };
        ContractStorageValue: {
            /** @description Base64-encoded XDR LedgerKey this value was read from */
            storage_key: string;
            /** @description Human-readable decoded storage key */
            key: unknown;
            /** @description Human-readable decoded value (absent when the entry was removed) */
            value: unknown;
            /**
             * Format: int64
             * @description Ledger sequence at which this value was observed
             */
            ledger_sequence: number;
            /**
             * Format: date-time
             * @description Timestamp this snapshot row was recorded
             */
            observed_at: string;
        };
        ContractStatsResponse: {
            /** @description Contracts sorted by event count (descending) */
            contracts: components["schemas"]["ContractStats"][];
            /**
             * Format: int64
             * @description Lower bound of queried ledger range
             */
            from_ledger: number;
            /**
             * Format: int64
             * @description Upper bound of queried ledger range
             */
            to_ledger: number;
            /**
             * @description Network queried
             * @enum {string}
             */
            network: "testnet" | "mainnet";
            /**
             * Format: date-time
             * @description Timestamp when response was generated
             */
            generated_at: string;
            /** @description Whether more pages are available */
            has_more: boolean;
            /** @description Opaque cursor to pass as the cursor parameter for the next page */
            next_cursor?: string | null;
        };
        ContractStats: {
            /** @description Soroban contract address */
            contract_id: string;
            /**
             * Format: int64
             * @description Total events for this contract in range
             */
            event_count: number;
            /**
             * Format: int64
             * @description Latest ledger sequence for this contract
             */
            last_seen_ledger: number;
            /**
             * Format: date-time
             * @description Timestamp of last event for this contract
             */
            last_seen_at: string;
            /** Format: int64 */
            invocation_count: number | null;
            /** Format: int64 */
            total_fee_charged: number | null;
            /** Format: double */
            avg_fee_charged: number | null;
            /** Format: double */
            avg_cpu_instructions: number | null;
            /** Format: double */
            avg_read_bytes: number | null;
            /** Format: double */
            avg_write_bytes: number | null;
        };
        APIKeyResponse: {
            /** Format: uuid */
            id: string;
            key_prefix: string;
            /** @description Raw key, returned only at creation time. */
            key?: string;
            label: string;
            /** @enum {string} */
            network: "testnet" | "mainnet";
            rate_limit_tier: string;
            created_by?: string;
            /** Format: date-time */
            last_used_at: string | null;
            /** Format: int64 */
            request_count: number;
            /** Format: date-time */
            revoked_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ListAPIKeysResponse: {
            api_keys: components["schemas"]["APIKeyResponse"][];
            /** @description Whether another page is available. */
            has_more: boolean;
            /** @description Opaque cursor for the next page (null if has_more is false). */
            next_cursor: string | null;
        };
        ListContractsResponse: {
            contracts: components["schemas"]["ContractResponse"][];
            /** @description Whether another page is available. */
            has_more: boolean;
            /** @description Opaque cursor for the next page (null if has_more is false). */
            next_cursor: string | null;
        };
        AdminKeyUsageResponse: {
            /** Format: uuid */
            api_key_id: string;
            /** Format: date-time */
            from: string;
            /** Format: date-time */
            to: string;
            /** Format: int64 */
            total_requests: number;
            /**
             * Format: int64
             * @description Requests with status code < 400
             */
            successful_requests: number;
            /** @description Per-endpoint breakdown; empty when the window has no requests */
            by_endpoint: components["schemas"]["EndpointUsage"][];
        };
        EndpointUsage: {
            endpoint: string;
            /** Format: int64 */
            requests: number;
            avg_duration_ms: number;
        };
        ContractRegistrationRequest: {
            /** @description Contract address (C... strkey, 56 characters) */
            contract_id: string;
            /** @description Network scope; omitted or empty means all networks */
            network?: string;
            /** @description Human-readable label */
            label?: string;
            /**
             * Format: int64
             * @description Ledger sequence to start indexing from
             * @default 0
             */
            index_from: number;
        };
        ContractResponse: {
            /** Format: uuid */
            id: string;
            /** @description Stellar contract id (C... strkey). */
            contract_id: string;
            network?: string | null;
            label?: string | null;
            /**
             * Format: int64
             * @description Ledger sequence indexing began from.
             */
            index_from: number;
            /** Format: date-time */
            created_at: string;
        };
        ContractCallRequest: {
            /** @description Contract function name to invoke */
            function: string;
            /** @description Base64-encoded XDR ScVal arguments, in order */
            args?: string[];
        };
        ContractCallResponse: {
            /** @description False when the simulation itself reported a failure (still HTTP 200) */
            success: boolean;
            /** @description Decoded return value; omitted when undecodable or failed */
            result?: unknown;
            /** @description Raw base64 XDR of the return value; omitted on failure */
            raw_xdr?: string;
            /** @description Simulation error message; present only when success=false */
            error?: string;
        };
        WebhookSubscription: {
            /** Format: uuid */
            id: string;
            /** @description Omitted when empty */
            apiKeyId?: string;
            contractId: string;
            /** @description Topic filter; omitted when unfiltered */
            topic0?: string | null;
            targetUrl: string;
            /** @description HMAC signing secret for deliveries; omitted when empty */
            secret?: string;
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description Present while deliveries are paused
             */
            pausedAt?: string | null;
            network: string;
        };
        WebhookCreateRequest: {
            contractId: string;
            /** @description Optional topic filter */
            topic0?: string | null;
            /** @description Delivery target; must be https with a publicly resolvable, non-private host */
            targetUrl: string;
            /** @default testnet */
            network: string;
        };
        WebhookCreateResponse: {
            /** Format: uuid */
            id: string;
            /** @description HMAC signing secret — shown here and in the listing */
            secret: string;
            targetUrl: string;
            contractId: string;
            network: string;
        };
        WebhookDelivery: {
            /** Format: int64 */
            id: number;
            /** Format: uuid */
            subscriptionId: string;
            eventId: string;
            attempt: number;
            attempts: number;
            status: string;
            /** @description HTTP status of the delivery attempt; omitted when none occurred */
            statusCode?: number | null;
            /** @description Omitted when empty */
            responseBody?: string;
            /** Format: date-time */
            deliveredAt: string;
            success: boolean;
        };
        WebhookRotateSecretResponse: {
            /** Format: uuid */
            id: string;
            /** @description The new primary signing secret (whsec_ prefixed) */
            secret: string;
            /** @description The demoted secret, now serving as secondary during the overlap window */
            previousSecret: string;
        };
        WebhookStatusResponse: {
            /** @enum {string} */
            status: "paused" | "resumed";
        };
        WebhookReplayResponse: {
            success: boolean;
            /** @enum {string} */
            status: "success" | "failed";
            attempt: number;
            /** @description 0 when no HTTP response occurred */
            status_code: number;
            /** @description Truncated to 500 characters */
            response_body: string;
        };
        ErrorResponse: {
            error: {
                /** @description Error code (e.g., INVALID_ARGUMENT, INTERNAL, UNAVAILABLE, CONFLICT) */
                code: string;
                /** @description Human-readable error message */
                message: string;
                /** @description Request ID for debugging */
                request_id?: string;
            };
        };
    };
    responses: {
        /** @description Invalid request parameters */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Requested resource was not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limit exceeded for this API key's tier (error.code RATE_LIMITED). Carries the same X-RateLimit-* headers as a successful response (X-RateLimit-Remaining is 0) plus Retry-After. */
        RateLimitExceeded: {
            headers: {
                "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                "Retry-After": components["headers"]["Retry-After"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Per-IP rate limit exceeded (error.code RATE_LIMITED). Applies to endpoints not covered by per-API-key limiting (public endpoints, or admin endpoints authenticated via ADMIN_API_KEY rather than X-API-Key) — only Retry-After is set, no X-RateLimit-* headers. */
        TooManyRequestsIPOnly: {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Service temporarily unavailable — either a dependency (database, Redis, gRPC backend) is down, or the server is shedding load under the global concurrency cap. When load-shedding is the cause, Retry-After is set; otherwise it is absent. */
        ServiceUnavailable: {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The supplied Idempotency-Key was already used with a request that does not match this one (error.code CONFLICT). Retry with a new key, or resend the exact original request body to get the original response replayed instead (issue #225). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /**
         * @description Opt-in de-duplication for retried create requests (issue #225). A retry carrying the same key and an identical request body replays the original response (see the `Idempotent-Replayed: true` response header) instead of creating a second resource. The same key reused with a different body is rejected with 409 Conflict. Keys are remembered for 24 hours; max length 255 characters.
         * @example 7da8f2b1-2e3c-4b8a-9f0d-6a1e5c3d9b7f
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: {
        /**
         * @description Requests allowed per window for this API key's rate-limit tier. Present on every response from an endpoint secured by ApiKeyAuth (2xx and 429 alike) once a valid X-API-Key was presented.
         * @example 50
         */
        "X-RateLimit-Limit": number;
        /**
         * @description Requests remaining in the current window for this API key. 0 on the response that triggers a 429.
         * @example 12
         */
        "X-RateLimit-Remaining": number;
        /**
         * @description Unix timestamp (seconds) when the current rate-limit window resets.
         * @example 1732900000
         */
        "X-RateLimit-Reset": number;
        /**
         * @description Seconds to wait before retrying. Present on 429 (rate limit exceeded, per-API-key or per-IP) and on 503 responses caused by the global concurrency cap shedding load. Not present on a 503 caused by an unavailable dependency (database/Redis/gRPC backend) — check the error envelope's `error.code` to distinguish the two.
         * @example 1
         */
        "Retry-After": number;
        /**
         * @description Whether this response was served from the Redis response cache (HIT) or freshly computed (MISS). Only emitted by endpoints that cache their response.
         * @example HIT
         */
        "X-Cache": "HIT" | "MISS";
        /**
         * @description Present and set to "true" only when this response was replayed from a prior request carrying the same Idempotency-Key (issue #225). Absent on the original (first) execution.
         * @example true
         */
        "Idempotent-Replayed": "true";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process is alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
            429: components["responses"]["TooManyRequestsIPOnly"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All dependencies reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"];
                };
            };
            429: components["responses"]["TooManyRequestsIPOnly"];
            /** @description Either one or more dependencies is unreachable (ReadyResponse body, status "degraded", the failing entry in checks set to "error: ..."), or the server is shedding load under the global concurrency cap (ErrorResponse body, Retry-After header set) — the same outermost load-shedding behavior every endpoint shares. */
            503: {
                headers: {
                    "Retry-After": components["headers"]["Retry-After"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadyResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Build metadata for the running instance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                /**
                 * @description Filter by Soroban contract address (strkey format, 56 chars starting with C)
                 * @example CA7QYNF7SOWQ3GLR2BGMZEHXAVIRZA4KVWLTJJFC7MGXUA74P7UJVSGZ
                 */
                contractId?: string;
                /** @description Filter by primary topic (XDR-encoded) */
                topic0?: string;
                /** @description Filter by secondary topic (XDR-encoded) */
                topic1?: string;
                /** @description Lower bound of ledger range (inclusive) */
                ledgerFrom?: number;
                /** @description Upper bound of ledger range (inclusive) */
                ledgerTo?: number;
                /** @description Maximum number of events to return */
                limit?: number;
                /** @description Opaque pagination cursor from previous response's next_cursor (for next page) */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of events with pagination metadata */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /**
                 * @description Event UUID (v4)
                 * @example 550e8400-e29b-41d4-a716-446655440000
                 */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Event details */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        event: components["schemas"]["SorobanEvent"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Event not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    streamEvents: {
        parameters: {
            query: {
                /** @description Contract to subscribe to */
                contractId: string;
                /** @description Optional topic filter */
                topic0?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events stream */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    batchGetEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description List of event UUIDs. Duplicates are deduplicated on first occurrence; the 100-id limit counts duplicates. */
                    ids: string[];
                };
            };
        };
        responses: {
            /**
             * @description Batch result. Always returns 200 even when some IDs are not found;
             *     check `missing` for unresolved IDs.
             */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Found events, in request order (deduplicated). */
                        events: components["schemas"]["SorobanEvent"][];
                        /** @description Ids that are valid UUIDs but not indexed, in request order. Empty array when every id was found. */
                        missing: string[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getContractEventSchemas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Soroban contract address */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contract event schema registry entry. Cached for 5 minutes (issue #221) — see X-Cache. */
            200: {
                headers: {
                    "X-Cache": components["headers"]["X-Cache"];
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractEventSchemaResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getContractSpec: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Soroban contract address */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contract spec and detected interfaces. Cached for 5 minutes (issue #221) — see X-Cache. */
            200: {
                headers: {
                    "X-Cache": components["headers"]["X-Cache"];
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractSpecResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["RateLimitExceeded"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getContractStorageLatest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Soroban contract address */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest known value per storage key */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractStorageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getContractStorageHistory: {
        parameters: {
            query: {
                /** @description Storage key to fetch history for, as returned by the storage/spec endpoints */
                key: string;
                /** @description Maximum number of history entries to return */
                limit?: number;
                /** @description Opaque pagination cursor from previous response's next_cursor (for next page) */
                cursor?: string;
            };
            header?: never;
            path: {
                /** @description Soroban contract address */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recorded changes for the requested storage key */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractStorageHistoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getIndexerStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Indexer statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexerStatsResponse"];
                };
            };
            429: components["responses"]["TooManyRequestsIPOnly"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getContractStats: {
        parameters: {
            query?: {
                /** @description Lower bound of ledger range (inclusive, default 0 for all time) */
                from_ledger?: number;
                /** @description Upper bound of ledger range (inclusive, default latest indexed) */
                to_ledger?: number;
                /** @description Network to query */
                network?: "testnet" | "mainnet";
                /** @description Number of top contracts to return */
                limit?: number;
                /** @description Opaque pagination cursor from previous response's next_cursor (for next page) */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Contract activity statistics. X-Cache indicates whether this response was served from the 60s Redis response cache (HIT) or freshly computed (MISS). */
            200: {
                headers: {
                    "X-RateLimit-Limit": components["headers"]["X-RateLimit-Limit"];
                    "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                    "X-RateLimit-Reset": components["headers"]["X-RateLimit-Reset"];
                    "X-Cache": components["headers"]["X-Cache"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractStatsResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listApiKeys: {
        parameters: {
            query?: {
                limit?: number;
                /** @description Opaque pagination cursor from a previous response's next_cursor. */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Page of API keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAPIKeysResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequestsIPOnly"];
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Opt-in de-duplication for retried create requests (issue #225). A retry carrying the same key and an identical request body replays the original response (see the `Idempotent-Replayed: true` response header) instead of creating a second resource. The same key reused with a different body is rejected with 409 Conflict. Keys are remembered for 24 hours; max length 255 characters.
                 * @example 7da8f2b1-2e3c-4b8a-9f0d-6a1e5c3d9b7f
                 */
                "Idempotency-Key"?: components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Human-readable label for this key */
                    label?: string;
                    /**
                     * @description Network this key is associated with
                     * @default mainnet
                     * @enum {string}
                     */
                    network?: "testnet" | "mainnet";
                    /**
                     * @description Rate limit tier for this key
                     * @default standard
                     * @enum {string}
                     */
                    rate_limit_tier?: "free" | "standard" | "premium" | "internal";
                };
            };
        };
        responses: {
            /** @description API key created */
            201: {
                headers: {
                    "Idempotent-Replayed": components["headers"]["Idempotent-Replayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequestsIPOnly"];
        };
    };
    deleteApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description API key ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API key deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            /** @description API key not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequestsIPOnly"];
        };
    };
    updateApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description API key ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description New display label for the key */
                    label?: string;
                    /** @description New rate-limit tier name */
                    rate_limit_tier?: string;
                };
            };
        };
        responses: {
            /** @description The updated API key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Admin API key is not configured on the server */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API key not found (or already revoked) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Request body exceeds the 1 MiB limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequestsIPOnly"];
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    getAdminDbStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Database statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        pools: {
                            [key: string]: unknown;
                        }[];
                        stats: {
                            [key: string]: unknown;
                        }[];
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequestsIPOnly"];
            /** @description The PgBouncer admin console could not be read. It is the upstream here, so a failure to reach it is a bad-gateway condition rather than an error in this service (see handlers/admin.go). */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The endpoint is not configured — ADMIN_API_KEY or PGBOUNCER_ADMIN_URL is unset, so no stats source exists. Deploying without PgBouncer is a supported configuration. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAdminKeyUsage: {
        parameters: {
            query: {
                /** @description Window start (RFC 3339) */
                from: string;
                /** @description Window end (RFC 3339); must be >= from, window <= 31 days */
                to: string;
            };
            header?: never;
            path: {
                /** @description API key ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage aggregates for the key over the window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminKeyUsageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequestsIPOnly"];
            /** @description Usage query failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listAdminContracts: {
        parameters: {
            query?: {
                /** @description Page size */
                limit?: number;
                /** @description Opaque pagination cursor from a previous page's next_cursor */
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of registered contracts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListContractsResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequestsIPOnly"];
            /** @description Listing failed (including a malformed cursor) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    createAdminContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractRegistrationRequest"];
            };
        };
        responses: {
            /** @description Contract registered (created or updated) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Request body exceeds the 1 MiB limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["TooManyRequestsIPOnly"];
            /** @description Registration failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    deleteAdminContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Contract registration ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registration removed (or never existed) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequestsIPOnly"];
            /** @description Delete failed (including a malformed registration ID) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    callContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Contract address (C... strkey, 56 characters) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContractCallRequest"];
            };
        };
        responses: {
            /** @description Simulation completed (including simulation-level failures, which report success=false with an error message) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContractCallResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Request body exceeds the 1 MiB limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            /** @description Soroban RPC call failed or returned no result */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listWebhooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscriptions owned by the calling key (null when none) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookSubscription"][] | null;
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
            /** @description Listing failed (plain-text body) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Database unavailable (plain-text body) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    createWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebhookCreateRequest"];
            };
        };
        responses: {
            /** @description Subscription created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookCreateResponse"];
                };
            };
            /** @description Invalid body or target URL (plain-text body) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description Request body exceeds the 1 MiB limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            /** @description Creation failed (plain-text body) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Database unavailable (plain-text body) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    deleteWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Subscription ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscription deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Subscription not found (plain-text body) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            /** @description Delete failed (plain-text body) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    rotateWebhookSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Subscription ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Secret rotated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookRotateSecretResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description No subscription with this ID belongs to the caller's API key (plain-text body) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            /** @description Rotation failed (plain-text body) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    pauseWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Subscription ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deliveries paused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookStatusResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
            /** @description Update failed (plain-text body) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    resumeWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Subscription ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deliveries resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookStatusResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
            /** @description Update failed (plain-text body) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listWebhookDeliveries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Subscription ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent delivery attempts (null when none) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookDelivery"][] | null;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
            /** @description Listing failed (plain-text body) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            503: components["responses"]["ServiceUnavailable"];
        };
    };
    listWebhookDeadLetters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Subscription ID */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dead-lettered delivery attempts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookDelivery"][];
                };
            };
            /** @description Missing webhook ID (plain-text body) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimitExceeded"];
            /** @description Listing failed (plain-text body) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Database unavailable (plain-text body) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    replayWebhookDeadLetter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Subscription ID */
                id: string;
                /** @description Numeric delivery ID from the dead-letters listing */
                deliveryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replay attempted; success reflects the delivery outcome */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebhookReplayResponse"];
                };
            };
            /** @description Missing webhook or delivery ID (plain-text body) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description No matching dead-lettered delivery (plain-text body) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            429: components["responses"]["RateLimitExceeded"];
            /** @description Replay failed to record (plain-text body) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Database unavailable (plain-text body) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain; version=0.0.4; charset=utf-8": string;
                };
            };
        };
    };
}
