#!/usr/bin/env bash
#
# Fail when database/schema.sql no longer matches what the migration chain
# actually builds (issues #436, #246).
#
# Why this exists
# ---------------
# schema.sql is the human-readable reference for the database. It was re-synced
# to the migration chain in #191, but nothing kept it in sync afterwards — and
# drift is not merely cosmetic. Issue #437 was exactly this failure in the
# other direction: schema.sql correctly listed six indexes on soroban_events
# that migration 0017 had silently stopped creating, and nothing compared the
# two, so the database ran without them for 9 migrations.
#
# This check builds a database from the migration chain, introspects what it
# actually contains, and compares that against schema.sql. A mismatch fails.
#
# What is compared
# ----------------
# Structural facts, not raw text: tables, columns (name, type, nullability),
# indexes, and constraints. Comparing `pg_dump` output directly would be
# brittle — dump formatting shifts between server versions and reorders freely,
# which produces failures that say nothing about the schema.
#
# Usage:
#   scripts/check-schema-drift.sh
#
# Requires DATABASE_URL pointing at a scratch database this script may DROP and
# recreate objects in. Intended for CI; running it against anything you care
# about will destroy data.

set -euo pipefail

DB_URL="${DATABASE_URL:-}"
MIGRATIONS_DIR="${MIGRATIONS_DIR:-database/migrations}"
SCHEMA_FILE="${SCHEMA_FILE:-database/schema.sql}"

if [ -z "$DB_URL" ]; then
    echo "error: DATABASE_URL must be set to a scratch database" >&2
    exit 2
fi

# The connection string is passed with -d rather than as a bare argument:
# some psql builds (notably the EDB Windows binaries) stop parsing flags once
# they see a positional dbname, silently ignoring everything after it.
command -v psql >/dev/null 2>&1 || {
    echo "error: psql is required" >&2
    exit 2
}

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

# Introspect a schema into a stable, diffable description.
#
# Ordering is explicit everywhere so the output is deterministic regardless of
# how the server happens to store or return rows.
introspect() {
    local schema="$1" out="$2"
    psql -d "$DB_URL" -X -q -t -A -F'|' -v ON_ERROR_STOP=1 -o "$out" <<SQL
-- Columns
SELECT 'column|' || c.relname || '|' || a.attname || '|'
       || format_type(a.atttypid, a.atttypmod) || '|'
       || CASE WHEN a.attnotnull THEN 'NOT NULL' ELSE 'NULL' END
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  JOIN pg_attribute a ON a.attrelid = c.oid
 WHERE n.nspname = '$schema'
   AND c.relkind IN ('r','p')
   -- Partition children are generated by create_soroban_partition(), not
   -- authored in schema.sql. Comparing them would demand that a documentation
   -- file enumerate every partition the chain happens to have created.
   AND c.relname !~ '^soroban_events_(p[0-9]|default$)'
   AND a.attnum > 0
   AND NOT a.attisdropped
 ORDER BY c.relname, a.attname;

-- Indexes. indexdef is normalised: the schema qualification and the table's
-- own name vary between the two databases being compared, not the structure.
-- The scratch schema name differs between the two databases being compared,
-- so it is stripped from every definition before diffing; otherwise identical
-- objects would show up as differences.
-- Constraint and index *names* on soroban_events carry a '_new' suffix in the
-- migration-built database: migration 0017 created the partitioned table as
-- soroban_events_new and renamed it, and PostgreSQL does not rename a table's
-- constraints along with it. The names are a historical artifact, not a
-- structural difference, so they are normalised before comparison.
SELECT 'index|' || tablename || '|' || replace(indexname, 'soroban_events_new', 'soroban_events') || '|'
       || replace(
            regexp_replace(indexdef, '^CREATE (UNIQUE )?INDEX [^ ]+ ON [^ ]+ ', 'IDX '),
            '$schema.', '')
  FROM pg_indexes
 WHERE schemaname = '$schema'
   AND tablename !~ '^soroban_events_(p[0-9]|default$)'
 ORDER BY tablename, indexname;

-- Constraints
SELECT 'constraint|' || rel.relname || '|' || replace(con.conname, 'soroban_events_new', 'soroban_events') || '|'
       || replace(pg_get_constraintdef(con.oid), '$schema.', '')
  FROM pg_constraint con
  JOIN pg_class rel ON rel.oid = con.conrelid
  JOIN pg_namespace n ON n.oid = rel.relnamespace
 WHERE n.nspname = '$schema'
   AND rel.relname !~ '^soroban_events_(p[0-9]|default$)'
 ORDER BY rel.relname, con.conname;
SQL
    sort -o "$out" "$out"
}

echo "==> Building schema from the migration chain"
psql -d "$DB_URL" -X -q -v ON_ERROR_STOP=1 \
    -c "DROP SCHEMA IF EXISTS drift_migrations CASCADE; CREATE SCHEMA drift_migrations;" \
    >/dev/null

for f in "$MIGRATIONS_DIR"/*.sql; do
    if ! PGOPTIONS="--search_path=drift_migrations,public" \
        psql -d "$DB_URL" -X -q -v ON_ERROR_STOP=1 -f "$f" >"$workdir/mig.log" 2>&1; then
        echo "error: migration $(basename "$f") failed to apply:" >&2
        tail -20 "$workdir/mig.log" >&2
        exit 1
    fi
done

echo "==> Building schema from schema.sql"
psql -d "$DB_URL" -X -q -v ON_ERROR_STOP=1 \
    -c "DROP SCHEMA IF EXISTS drift_schema CASCADE; CREATE SCHEMA drift_schema;" \
    >/dev/null

if ! PGOPTIONS="--search_path=drift_schema,public" \
    psql -d "$DB_URL" -X -q -v ON_ERROR_STOP=1 -f "$SCHEMA_FILE" >"$workdir/schema.log" 2>&1; then
    echo "error: $SCHEMA_FILE failed to apply to an empty database:" >&2
    tail -20 "$workdir/schema.log" >&2
    exit 1
fi

echo "==> Comparing"
introspect drift_migrations "$workdir/from-migrations.txt"
introspect drift_schema "$workdir/from-schema.txt"

psql -d "$DB_URL" -X -q -v ON_ERROR_STOP=1 \
    -c "DROP SCHEMA IF EXISTS drift_migrations CASCADE; DROP SCHEMA IF EXISTS drift_schema CASCADE;" \
    >/dev/null

if diff -u "$workdir/from-schema.txt" "$workdir/from-migrations.txt" > "$workdir/drift.diff"; then
    echo
    echo "OK: schema.sql matches the migration chain."
    exit 0
fi

cat >&2 <<EOF

FAIL: database/schema.sql has drifted from the migration chain.

  '-' lines are in schema.sql but NOT produced by the migrations
  '+' lines are produced by the migrations but MISSING from schema.sql

EOF
cat "$workdir/drift.diff" >&2
cat >&2 <<EOF

This is the check that would have caught #437, where schema.sql listed six
indexes on soroban_events that migration 0017 had silently stopped creating.

Fix whichever side is wrong — usually schema.sql needs regenerating, but a '-'
line can equally mean a migration failed to do what it intended.
EOF
exit 1
